<?php

function sum_menu(){
    $item = array();
    $item['sum_form'] = [
        'title' => 'Sum Form',
        'page callback' => 'drupal_get_form',
        'page arguments' => ['sum_form'],
        'access callback' => TRUE,
        'type' => MENU_NORMAL_ITEM,
    ];
    $item['sum_success'] = [
        'title' => 'Sum Results',
        'page callback' => 'sum_results',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    ];

    return $item;
}

function sum_form() {
    $form['left_number'] = array(
        '#title' => 'Left number',
        '#type' => 'textfield',
        '#description' => t('Please enter your starting number.'),
        '#element_validate' => array('element_validate_integer'),
        '#required' => TRUE,
    );
    $form['right_number'] = array(
        '#title' => 'Right number',
        '#type' => 'textfield',
        '#description' => t('Please enter a number to add to the starting number.'),
        '#element_validate' => array('element_validate_integer'),
        '#required' => TRUE,
    );

    $form['submit'] = array(
        '#type' => 'submit',
        '#value' => 'Calculate Sum',
    );

    return $form;
}

function sum_form_submit($form, &$form_state) {
    $left_number = $form_state['values']['left_number'];
    $right_number = $form_state['values']['right_number'];

    $_SESSION['sum'] = $left_number + $right_number;

    $form_state['redirect'] = 'sum_success';
}

function sum_results() {
    $sum = $_SESSION['sum'];

    return "<p>The sum is $sum</p>";
}
