<?php

function sum_menu(){
    $item = array();
    $item['sum_form'] = [
        'title' => 'Sum Form',
        'page callback' => 'drupal_get_form',
        'page arguments' => ['sum_form'],
        'access callback' => TRUE,
        'type' => MENU_NORMAL_ITEM,
    ];
    $item['sum_success'] = [
        'title' => 'Sum Results',
        'page callback' => 'sum_results',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    ];

    return $item;
}

function sum_form() {
    $form['left_number'] = array(
        '#title' => 'Left number',
        '#type' => 'textfield',
        '#description' => t('Please enter your starting number.'),
        '#element_validate' => array('element_validate_number', 'element_validate_range', 'element_validate_even'),
        '#required' => TRUE,
    );
    $form['right_number'] = array(
        '#title' => 'Right number',
        '#type' => 'textfield',
        '#description' => t('Please enter a number to add to the starting number.'),
        '#element_validate' => array('element_validate_number', 'element_validate_range', 'element_validate_even'),
        '#required' => TRUE,
    );

    $form['submit'] = array(
        '#type' => 'submit',
        '#value' => 'Calculate Sum',
    );

    return $form;
}

function sum_form_submit($form, &$form_state) {
    $left_number = $form_state['values']['left_number'];
    $right_number = $form_state['values']['right_number'];

    $_SESSION['sum'] = $left_number + $right_number;

    $form_state['redirect'] = 'sum_success';
}

function sum_results() {
    $sum = $_SESSION['sum'];

    return "<p>The sum is $sum</p>";
}

function element_validate_range($element) {
    if ($element['#value'] > 50 || $element['#value'] <-50) {
        form_error($element, t('Number must be less than 50 or greater than -50.'));
    }
}

function element_validate_even($element) {
    if ($element['#value'] % 2 != 0) {
        form_error($element, t($element['#title'] . ': The number must be even.'));
    }
}
